### ISSUE TITLE
[tracking] 1.12.0 doc updates

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#1166]
### Description

This is the tracking issue for major 1.12 features:

- [x] https://github.com/kyverno/website/issues/1146
- [x] https://github.com/kyverno/website/pull/1152
- [x] https://github.com/kyverno/website/pull/1157
- [x] https://github.com/kyverno/website/pull/1126
- [x] https://github.com/kyverno/website/pull/1119, https://github.com/kyverno/website/pull/1134
- [x] https://github.com/kyverno/website/issues/1165
  - [x] https://github.com/kyverno/website/pull/1037
  - [x] https://github.com/kyverno/website/pull/1156
